<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PuppetsMakersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $puppets = 105; $makers = 45;
        $puppetMakerData = [
            ['puppet_id' => 1, 'maker_id' => 19],
            ['puppet_id' => 2, 'maker_id' => 19],
            ['puppet_id' => 3, 'maker_id' => 19],
            ['puppet_id' => 4, 'maker_id' => 31],
            ['puppet_id' => 4, 'maker_id' => 33],
            ['puppet_id' => 5, 'maker_id' => 31],
            ['puppet_id' => 5, 'maker_id' => 33],
            ['puppet_id' => 6, 'maker_id' => 35],
            ['puppet_id' => 6, 'maker_id' => 32],
            ['puppet_id' => 6, 'maker_id' => 33],
            ['puppet_id' => 6, 'maker_id' => 34],
            ['puppet_id' => 7, 'maker_id' => 35],
            ['puppet_id' => 7, 'maker_id' => 32],
            ['puppet_id' => 7, 'maker_id' => 33],
            ['puppet_id' => 7, 'maker_id' => 34],
            ['puppet_id' => 8, 'maker_id' => 15],
            ['puppet_id' => 9, 'maker_id' => 15],
            ['puppet_id' => 10, 'maker_id' => 22],
            ['puppet_id' => 10, 'maker_id' => 22],
            ['puppet_id' => 11, 'maker_id' => 22],
            ['puppet_id' => 11, 'maker_id' => 22],
            ['puppet_id' => 12, 'maker_id' => 36],
            ['puppet_id' => 12, 'maker_id' => 5],
            ['puppet_id' => 12, 'maker_id' => 37],
            ['puppet_id' => 12, 'maker_id' => 2],
            ['puppet_id' => 12, 'maker_id' => 41],
            ['puppet_id' => 12, 'maker_id' => 28],
            ['puppet_id' => 13, 'maker_id' => 6],
            ['puppet_id' => 14, 'maker_id' => 6],
            ['puppet_id' => 15, 'maker_id' => 14],
            ['puppet_id' => 16, 'maker_id' => 14],
            ['puppet_id' => 17, 'maker_id' => 8],
            ['puppet_id' => 18, 'maker_id' => 19],
            ['puppet_id' => 19, 'maker_id' => 21],
            ['puppet_id' => 20, 'maker_id' => 22],
            ['puppet_id' => 20, 'maker_id' => 22],
            ['puppet_id' => 21, 'maker_id' => 22],
            ['puppet_id' => 22, 'maker_id' => 35],
            ['puppet_id' => 23, 'maker_id' => 35],
            ['puppet_id' => 24, 'maker_id' => 36],
            ['puppet_id' => 25, 'maker_id' => 38],
            ['puppet_id' => 25, 'maker_id' => 39],
            ['puppet_id' => 26, 'maker_id' => 38],
            ['puppet_id' => 26, 'maker_id' => 39],
            ['puppet_id' => 27, 'maker_id' => 22],
            ['puppet_id' => 28, 'maker_id' => 7],
            ['puppet_id' => 28, 'maker_id' => 31],
            ['puppet_id' => 28, 'maker_id' => 11],
            ['puppet_id' => 28, 'maker_id' => 33],
            ['puppet_id' => 29, 'maker_id' => 22],
            ['puppet_id' => 30, 'maker_id' => 29],
            ['puppet_id' => 31, 'maker_id' => 29],
            ['puppet_id' => 31, 'maker_id' => 33],
            ['puppet_id' => 32, 'maker_id' => 3],
            ['puppet_id' => 33, 'maker_id' => 17],
            ['puppet_id' => 33, 'maker_id' => 10],
            ['puppet_id' => 34, 'maker_id' => 29],
            ['puppet_id' => 34, 'maker_id' => 33],
            ['puppet_id' => 35, 'maker_id' => 6],
            ['puppet_id' => 36, 'maker_id' => 36],
            ['puppet_id' => 36, 'maker_id' => 5],
            ['puppet_id' => 36, 'maker_id' => 37],
            ['puppet_id' => 36, 'maker_id' => 2],
            ['puppet_id' => 36, 'maker_id' => 41],
            ['puppet_id' => 36, 'maker_id' => 28],
            ['puppet_id' => 37, 'maker_id' => 35],
            ['puppet_id' => 37, 'maker_id' => 29],
            ['puppet_id' => 37, 'maker_id' => 33],
            ['puppet_id' => 38, 'maker_id' => 22],
            ['puppet_id' => 39, 'maker_id' => 22],
            ['puppet_id' => 40, 'maker_id' => 22],
            ['puppet_id' => 40, 'maker_id' => 41],
            ['puppet_id' => 41, 'maker_id' => 22],
            ['puppet_id' => 42, 'maker_id' => 29],
            ['puppet_id' => 42, 'maker_id' => 33],
            ['puppet_id' => 43, 'maker_id' => 6],
            ['puppet_id' => 44, 'maker_id' => 40],
            ['puppet_id' => 45, 'maker_id' => 9],
            ['puppet_id' => 45, 'maker_id' => 30],
            ['puppet_id' => 46, 'maker_id' => 19],
            ['puppet_id' => 47, 'maker_id' => 25],
            ['puppet_id' => 47, 'maker_id' => 37],
            ['puppet_id' => 48, 'maker_id' => 7],
            ['puppet_id' => 48, 'maker_id' => 31],
            ['puppet_id' => 48, 'maker_id' => 11],
            ['puppet_id' => 48, 'maker_id' => 33],
            ['puppet_id' => 49, 'maker_id' => 17],
            ['puppet_id' => 49, 'maker_id' => 29],
            ['puppet_id' => 49, 'maker_id' => 33],
            ['puppet_id' => 50, 'maker_id' => 12],
            ['puppet_id' => 51, 'maker_id' => 17],
            ['puppet_id' => 51, 'maker_id' => 29],
            ['puppet_id' => 51, 'maker_id' => 33],
            ['puppet_id' => 52, 'maker_id' => 8],
            ['puppet_id' => 52, 'maker_id' => 19],
            ['puppet_id' => 53, 'maker_id' => 22],
            ['puppet_id' => 54, 'maker_id' => 36],
            ['puppet_id' => 54, 'maker_id' => 5],
            ['puppet_id' => 55, 'maker_id' => 22],
            ['puppet_id' => 56, 'maker_id' => 22],
            ['puppet_id' => 57, 'maker_id' => 8],
            ['puppet_id' => 57, 'maker_id' => 19],
            ['puppet_id' => 58, 'maker_id' => 19],
            ['puppet_id' => 59, 'maker_id' => 19],
            ['puppet_id' => 60, 'maker_id' => 12],
            ['puppet_id' => 61, 'maker_id' => 19],
            ['puppet_id' => 62, 'maker_id' => 41],
            ['puppet_id' => 62, 'maker_id' => 13],
            ['puppet_id' => 63, 'maker_id' => 13],
            ['puppet_id' => 64, 'maker_id' => 8],
            ['puppet_id' => 64, 'maker_id' => 19],
            ['puppet_id' => 65, 'maker_id' => 19],
            ['puppet_id' => 66, 'maker_id' => 19],
            ['puppet_id' => 67, 'maker_id' => 20],
            ['puppet_id' => 67, 'maker_id' => 37],
            ['puppet_id' => 68, 'maker_id' => 23],
            ['puppet_id' => 68, 'maker_id' => 19],
            ['puppet_id' => 69, 'maker_id' => 6],
            ['puppet_id' => 70, 'maker_id' => 42],
            ['puppet_id' => 70, 'maker_id' => 22],
            ['puppet_id' => 71, 'maker_id' => 19],
            ['puppet_id' => 71, 'maker_id' => 6],
            ['puppet_id' => 72, 'maker_id' => 22],
            ['puppet_id' => 73, 'maker_id' => 22],
            ['puppet_id' => 74, 'maker_id' => 35],
            ['puppet_id' => 74, 'maker_id' => 29],
            ['puppet_id' => 74, 'maker_id' => 33],
            ['puppet_id' => 75, 'maker_id' => 16],
            ['puppet_id' => 76, 'maker_id' => 31],
            ['puppet_id' => 76, 'maker_id' => 17],
            ['puppet_id' => 77, 'maker_id' => 22],
            ['puppet_id' => 78, 'maker_id' => 11],
            ['puppet_id' => 78, 'maker_id' => 7],
            ['puppet_id' => 78, 'maker_id' => 31],
            ['puppet_id' => 78, 'maker_id' => 33],
            ['puppet_id' => 79, 'maker_id' => 11],
            ['puppet_id' => 79, 'maker_id' => 7],
            ['puppet_id' => 79, 'maker_id' => 31],
            ['puppet_id' => 79, 'maker_id' => 33],
            ['puppet_id' => 80, 'maker_id' => 36],
            ['puppet_id' => 80, 'maker_id' => 5],
            ['puppet_id' => 80, 'maker_id' => 37],
            ['puppet_id' => 80, 'maker_id' => 2],
            ['puppet_id' => 81, 'maker_id' => 35],
            ['puppet_id' => 81, 'maker_id' => 29],
            ['puppet_id' => 81, 'maker_id' => 33],
            ['puppet_id' => 82, 'maker_id' => 29],
            ['puppet_id' => 82, 'maker_id' => 33],
            ['puppet_id' => 83, 'maker_id' => 6],
            ['puppet_id' => 83, 'maker_id' => 40],
            ['puppet_id' => 84, 'maker_id' => 9],
            ['puppet_id' => 84, 'maker_id' => 30],
            ['puppet_id' => 85, 'maker_id' => 19],
            ['puppet_id' => 85, 'maker_id' => 6],
            ['puppet_id' => 86, 'maker_id' => 19],
            ['puppet_id' => 87, 'maker_id' => 25],
            ['puppet_id' => 87, 'maker_id' => 37],
            ['puppet_id' => 88, 'maker_id' => 7],
            ['puppet_id' => 88, 'maker_id' => 31],
            ['puppet_id' => 88, 'maker_id' => 11],
            ['puppet_id' => 88, 'maker_id' => 33],
            ['puppet_id' => 89, 'maker_id' => 36],
            ['puppet_id' => 89, 'maker_id' => 5],
            ['puppet_id' => 89, 'maker_id' => 37],
            ['puppet_id' => 89, 'maker_id' => 2],
            ['puppet_id' => 90, 'maker_id' => 22],
            ['puppet_id' => 91, 'maker_id' => 29],
            ['puppet_id' => 91, 'maker_id' => 33],
            ['puppet_id' => 91, 'maker_id' => 34],
            ['puppet_id' => 92, 'maker_id' => 15],
            ['puppet_id' => 93, 'maker_id' => 6],
            ['puppet_id' => 94, 'maker_id' => 27],
            ['puppet_id' => 95, 'maker_id' => 43],
            ['puppet_id' => 95, 'maker_id' => 28],
            ['puppet_id' => 96, 'maker_id' => 44],
            ['puppet_id' => 97, 'maker_id' => 6],
            ['puppet_id' => 97, 'maker_id' => 40],
            ['puppet_id' => 98, 'maker_id' => 14],
            ['puppet_id' => 99, 'maker_id' => 9],
            ['puppet_id' => 99, 'maker_id' => 30],
            ['puppet_id' => 100, 'maker_id' => 8],
            ['puppet_id' => 101, 'maker_id' => 45],
            ['puppet_id' => 101, 'maker_id' => 4],
            ['puppet_id' => 102, 'maker_id' => 2],
            ['puppet_id' => 103, 'maker_id' => 1],
            ['puppet_id' => 104, 'maker_id' => 1],
            ['puppet_id' => 105, 'maker_id' => 29],
            ['puppet_id' => 105, 'maker_id' => 33],
        ];
        $puppetMakerDataFr = [];
        $puppetMakerDataEn = [];
        foreach ($puppetMakerData as $data) {
            $puppet_idFr = $data['puppet_id'] + $puppets;
            $maker_idFr = $data['maker_id'] + $makers;
            $puppet_idEn = $data['puppet_id'] + ($puppets*2);
            $maker_idEn = $data['maker_id'] + ($makers*2);
            $puppetMakerDataFr[] = ['puppet_id' => $puppet_idFr, 'maker_id' => $maker_idFr];
            $puppetMakerDataEn[] = ['puppet_id' => $puppet_idEn, 'maker_id' => $maker_idEn];
        }

        foreach ($puppetMakerData as $data) {
            DB::table('puppets_makers')->insert($data);
        }
        foreach ($puppetMakerDataFr as $data) {
            DB::table('puppets_makers')->insert($data);
        }
        foreach ($puppetMakerDataEn as $data) {
            DB::table('puppets_makers')->insert($data);
        }
    }
}
